### PR TITLE
New cookiecutter-aiohttp-uvloop template in docs

### PR DESCRIPTION
**Pull request by osminogin**
I'm glad to present to the community my template for python3 projects based on asyncio/aiohttp with uvloop (ultra fast event loop implementation). 

Read why [uvloop: Blazing fast Python networking](https://magic.io/blog/uvloop-blazing-fast-python-networking/), *TLDR* 
`In fact, it is at least 2x faster than nodejs, gevent, as well as any other Python asynchronous framework. The performance of uvloop-based asyncio is close to that of Go programs.`

Successfully used on several projects for high-load Public API, mobile app backends, but universally like aiohttp himself. I hope this will be useful to someone else.

### CODE REVIEW

**Comment by ssbarnea** [comment]
We are no longer listing templates in the readme, read https://github.com/cookiecutter/cookiecutter/blob/master/README.md#a-pantry-full-of-cookiecutters and just add the right topic to your repository on github.

**Comment by osminogin** [comment]
I think the project is really dead.

**Comment by osminogin** [comment]
Remove other templates from readme so segmented community members be in equal conditions. As developer I personally recomends that all just use yoman there project is alive and where projects templates can be useful.

**Comment by osminogin** [comment]
Yoman have ecosystem - cookiecutter is not.

**Comment by ssbarnea** [comment]
@osminogin With all due respect for alternatives, which I looked upon myself,  cookiecutter is not dead, is only in a transitional phase. Cookiecutter is python based and most its users like that, yoman is from JS world. Cookiecutter is a dependency of many python packages, which yoman will never be (unless there is a python port).

In number cookiecutter still has >11K start on github, while yoman does not even reach 1K.

Please read at least the project README when preparing a PR, the template listing was clearly documented there.

PS. About community..., we can do better, we messed few things like moving between chat platforms too often.

**Pull request closed without merging**
