### PR TITLE
Drop support for Python 3.7

### PR DESCRIPTION
**Pull request by danieleades**
drops support for python 3.7
python 3.7 is end of life

### CODE REVIEW

**Comment by danieleades** [comment]
> I think this is fine. @cookiecutter/cookie-monsters What do you think?

great group name

**Comment by ericof** [comment]
I'm 👍🏼 but I would like to test what happens with pipx in 3.7 trying to get the latest cookiecutter

**Review by ericof — APPROVED** [review]

**Comment by jensens** [comment]
According to Semantic Versioning this is a major change, right? I would prefer to wait for a 3.0 release to introduce this.

**Comment by danieleades** [comment]
i don't think there's any rush to merge this. It's dead easy to keep rebasing.

It really only becomes important once you want to use newer features, or you want to update the dependencies and those dependencies have dropped support for 3.7.

I personally drop EOF python versions like a hot brick, but it would be perfectly reasonable to hold onto it until it's actually causing an issue and then pull the cord on this PR

**Review by kurtmckee — APPROVED** [review]
@ericof / @jensens CI no longer passes because requests has known security bugs that are not getting released for Python 3.7. Let's get this merged and released.

@ericof The pipx question is easy: requiring Python 3.8 means that pipx on Python 3.7 will not find newer versions for installation.

@jensens This isn't a breaking change -- nobody on Python 3.7 could install this after release, so they won't see anything break. No need to wait for a v3 release.

I recommend merging this asap and releasing it.

**Comment by danieleades** [comment]
I'll get this cleaned up and rebased

**Review by jensens — APPROVED** [review]

**Pull request merged**
