### PR TITLE
Add a snap

### PR DESCRIPTION
**Pull request by evandandrea**
Hi! I stumbled across cookiecutter in a list of must-have console apps and it seemed cool but I couldn't find any packages. I work on [Snapcraft](https://github.com/snapcore/snapcraft), so I took the opportunity to make a snapcraft.yaml of it. If you build it locally and push to the [Snap Store](https://snapcraft.io/store) then the millions of Linux users who get Spotify, Slack, etc this way can also get cookiecutter.

To build:
`snap install snapcraft` from Ubuntu, or [install Multipass](https://github.com/CanonicalLtd/multipass/releases) then `brew install snapcraft` on MacOS. Run `snapcraft`.

To publish:
[Create an account](https://snapcraft.io/account), then:
```
snapcraft login
snapcraft register cookiecutter
snapcraft push --release=stable *.snap
```

Cheers!

### CODE REVIEW

**Comment by insspb** [comment]
@evandandrea thank you for this. In this case we will need to add it to our CI/CD to exclude manual work with it on updates.

**Comment by ssbarnea** [comment]
I will try to resolve this because it looks like a good distribution channel and snapcraft has CI integration, so we can test it. So I initiated two actions:

* requested activation of snapcraft bot on cookiecutter, probably @pydanny will need to approve
* requested access to "cookiecutter" reserved name on https://snapcraft.io for ssbarnea in order to test and activate the integrations.

Once these are done I will be able to test, without any need to configure credentails or new travis jobs, everything will be taken care of snapcraft/canonical.

**Comment by ssbarnea** [comment]
@evandandrea Can you please rebase it and push it again? Travis is still confused since the project move and close/reopen did not fix it.

**Comment by ssbarnea** [comment]
Closing due to lack of time to work on. I will reopen when I have time.

**Comment by ssbarnea** [comment]
Closing due to lack of time to work on. I will reopen when I have time.

**Comment by ssbarnea** [comment]
I am closing this because there are some distribution issues with snaps that prevent them from accessing data from $HOME. That prevented me from creating official snaps for two other projects. Is not that I am against it, but for the moment it does not make sense to keep it open.

**Pull request closed without merging**
