### PR TITLE
CI/CD: Tox -> Nox: Deprecate tox and related documentation updates

### LINKED ISSUE #1697: CI/CD: Tox -> Nox
We are python project, and working with python files should be easier for any python developer, over working with text configuration in tox.

### PR DESCRIPTION
**Pull request by insspb**
Closes #1697 

- Deprecates tox
- Update related contribution docs
- Reformat CONTRIBUTING.md
- Roadmap information is also removed, as not actual completely

### CODE REVIEW

**Comment by jensens** [comment]
Please stick to one sentence per line. We want to be inclusive and having translatable docs is important.

**Comment by insspb** [comment]
@jensens 

- I already commented and explained one line issues in #1677. And oneliners was implemented there. If I saw it before I never be agreed with this change. You decided and done, now you try to force it without reason.
- This is markdown file that could and should be readd from vscode, pycharm or other editor as helper and reminder... And what to do with 320 symbols in line? 
- Any already translated documentation?
- Any issue with request for translation?

Inclusive is good, but completely not related to one line. 

Technical documentation should be clear from any device, with any screen, without moving mouse. 

This PR implement 88 symbols, same as in black.

**Comment by jensens** [comment]
1. I dont force, its docs standard, stick to high standards?
2.  340 per line? Rephrase, nobody would read it
3.  Inclusiveness produces translatable documentation. You wont find a translator if docs does not enable it. 

So, why are you taking docs like code? Its just wrong. Its it not.

**Comment by insspb** [comment]
@jensens I am not arguing that this practice (one line) exist. I am sure, that this practice is not acceptable here at current step. This brings more complexity for working with docs. Docs require correct content at this point. As content will not be stable quite long.

Now I just opened three popular projects. Raw files. How many symbols inside?

- https://raw.githubusercontent.com/pytest-dev/pytest/main/CONTRIBUTING.rst
- https://raw.githubusercontent.com/celery/celery/master/CONTRIBUTING.rst
- https://raw.githubusercontent.com/psf/requests/main/README.md

So let's not reinvent a bike.

**Comment by jensens** [comment]
Come on, it does add complexity to no add manual linebreaks? Sorry, I did the work already, just stick to it. It makes it simpler. We are exact at this point. You started formatting back. 

Its that easy, write whole sentences and add a line break at the end of it. 

Its simpler than anything we do here.

Btw.: since you remove the Makefile in docs you also removed "make gettext". So, actually you removed a Sphinx default feature.

**Comment by ericof** [comment]
@insspb 
First, I do not see a reason to move from tox to nox, and I think this should be discussed more with the rest of the community. So let's get back to the issue and discuss there.
Second, please follow the guidelines @jensens mentioned about contributing to documentation.

**Comment by ericof** [comment]
Sorry, closed this by mistake.

**Comment by kurtmckee** [comment]
@jensens @ericof Please close this PR. There is no need to move from tox to nox.

**Comment by ericof** [comment]
We just need now to decide if we keep nox or not

**Pull request closed without merging**
