### PR TITLE
feat: Add resolved template repository path as _repo_dir to the context

### PR DESCRIPTION
**Pull request by tmeckel**
This PR contains a small change, which includes the resolved repository path from the `determine_repo_dir` as item `_repo_dir` to the Cookiecutter context. 

This allows to define Python packages in the template and to reference them by extending the `sys.path` with normal import statements, e.g. in hook scripts.

__Sample:__

```python
import os
import requests
import shutil
import sys

from dateutil import parser as dateparser

from subprocess import Popen

sys.path.append("{{ cookiecutter._repo_dir }}")  # <= extend sys.path

from utils.version import Version # <= use module from internal package

# Get the root project directory
PROJECT_DIRECTORY = os.path.realpath(os.path.curdir)

def _error_exit(msg):
    # exits with status 1 to indicate failure
    sys.stderr.write("ERROR: %s\n" % msg)
    sys.exit(1)
```

### CODE REVIEW

**Comment by tmeckel** [comment]
Someone @audreyfeldroy, @browniebroke, @ericof, @hackebrot, @insspb, @pydanny, @simobasso, @ssbarnea up to for a review of this mini PR, consisting of one line? 😁

**Review by ericof — APPROVED** [review]
LGTM

**Comment by tmeckel** [comment]
@ericof Érico when will this be available in a new release i.e. when will there be a new release?

**Comment by ericof** [comment]
@tmeckel We will sprint on the next weeks to get a new release out

**Comment by klaraward** [comment]
Hoping for this change in a new release soon :)

**Comment by klaraward** [comment]
Before this is released, is there any workaround whatsoever to get access to this in a hooks script?

**Comment by klaraward** [comment]
@ericof any hope a of release soon? 🙏

**Pull request merged**
