### PR TITLE
User's JSON parse error causes ugly Python exception #809

### PR DESCRIPTION
**Pull request by noone234**
Addresses issue #809. A malformed JSON file no longer raises an unhandled exception.

**Steps to reproduce the issue:**
1. Create a subtly malformed .json file in a project directory
2. Run cookiecutter on that project
3. Observe your eyes glazing over as a huge python exception comes out of it.

**Cause:**

In generate.py's generate_context() function, for a JSON decoding error, it raised a friendlier exception. That is still daunting to new users.

**Solution:**

Logs an error message and exits.

**Other things to note:**

The message text has not changed.

### CODE REVIEW

**Comment by insspb** [comment]
@noone234 thank you for contribution. At least now I understand what is #809 about.

You should not remove current Raise error, as cc can be used in internal scripts and this error can be handled in some kind. 
So when you remove raise - you making breaking change.

Correct way to implement this:
Detect is cc run as console app or as library. 
If console app - you current solution.

If as part of other product - only raise, as it was. 

@noone234 do you interested to continue work on this?

**Comment by noone234** [comment]
@insspb Thank you for reviewing my PR.

Yes, I am interested in continuing the work. I will try to do as you recommended.

**Comment by noone234** [comment]
After studying the source code further, I opted for a much simpler solution.

cli.py's main() function already catches several exceptions. I added `ContextDecodingException` to that list.

That has the desired effect.
- generate.py's generate_context() function still raises a `ContextDecodingException`, as @insspb requested.
- If `cookiecutter` is run as a command, it prints the friendlier error message as requested in https://github.com/cookiecutter/cookiecutter/issues/809. It also exits with a non-zero status.

**Comment by insspb** [comment]
@noone234 
Nice.
Tests?

**Comment by noone234** [comment]
Added a test in test_cli.py. It is adapted from tests_generate_context.py's test_generate_context_with_json_decoding_error().

I am not sure if this suffices.

**Comment by noone234** [comment]
Hi @insspb, I added a test in test_cli.py. Do you need anything else from me?

**Comment by insspb** [comment]
Hi @noone234 I am currently busy on other project. Will review after weekend.

**Comment by noone234** [comment]
@insspb bumping this PR. It has been a few weeks since last activity.

**Comment by noone234** [comment]
@insspb Can you please remove the `breaking-change` label from this PR? because it is no longer a breaking change.

Do you think you will still have time to review this PR? If not, what are my next steps?

Thank you.

**Comment by noone234** [comment]
@JonZeolla Sorry to interrupt. Can you please help me get this PR unstuck or direct me to someone who can? There has been no activity since October; 4 months.

**Comment by noone234** [comment]
@simobasso Hi, I'm reaching out for assistance. Can you please help me get this PR unstuck or direct me to someone who can? There has been no activity since October; 5 months.

Per the December 28 comment, can the `breaking-change` and `wip` labels be removed from this PR?

**Comment by simobasso** [comment]
Hey @noone234, 👋  thank you for reaching out!

Sadly I don't have any permission to help you 😞 as you can see on https://github.com/cookiecutter/cookiecutter/pull/1485 I'm in the same conditions.

One of the maintainers said https://github.com/cookiecutter/cookiecutter/pull/1485#issuecomment-812668296 that no one has time for this project now.

What can I do for you is to review your pr but I cannot merge it sorry.

**Review by simobasso — APPROVED** [review]

**Review by simobasso — APPROVED** [review]

**Comment by simobasso** [comment]
Hey @noone234 👋, just merged!

Thanks for your job and sorry 😅  about the delay, we will do better next time!

**Comment by noone234** [comment]
Thank you so much @simobasso!

I see that you are now a maintainer. Congratulations! 🎉

**Pull request merged**
