### PR TITLE
Generate Context fails when a default list value provided

### PR DESCRIPTION
**Pull request by simonwardjones**
Hi, I have never contributed to cookiecutter (or any open source to be honest) but gotta say i love cookiecutter.

Currently when including a list in a default context the generate context fails. For example if you had a default context as below with a list value for the "_copy_without_render" key.

```json
{
    "1": 2,
    "some_key": "some_val",
    "_copy_without_render": [
        "**/*.txt"
    ]
}
``` 

In particular in the cruft project there is currently an issue caused by this: https://github.com/cruft/cruft/issues/166

This PR updates the `apply_overwrites_to_context` and updates the tests such that when overwriting, if a list is given this overwrites the whole list.

### CODE REVIEW

**Comment by jensens** [comment]
remark: this PR fixes issue #1757

**Comment by A160989** [comment]
any update on getting this merged in?

**Comment by adamcunnington-mlg** [comment]
+1 still blocked by this

**Comment by luisdavim** [comment]
Any chances of getting this merged any time soon?

**Comment by simonwardjones** [comment]
Any chances of getting this merged any time soon?

**Comment by nialloriordanroo** [comment]
I'm also blocked by this

**Comment by s-agawane** [comment]
+1 still blocked by this.

**Pull request closed without merging**
