### PR TITLE
D100: Add missing docstring headers

### PR DESCRIPTION
**Pull request by croesnick**
Took the list generated by `pycodestyle --select=D100` and added docstrings for each entry. Also took the liberty to reorder imports in files touched to follow the usual order (builtin-external-internal, `import` before `from .. import ..`, lexicographical).

Solves GH-1269

### CODE REVIEW

**Comment by ssbarnea** [comment]
Please rework this and remove D100 from setup.cfg as part of it.

**Comment by croesnick** [comment]
Thanks @ssbarnea for noticing that I missed to re-enable the D100 style check in `setup.cfg`. Changed that 🙂.
You asked me to also do some rework. Could you give me some hints which parts need a rework?

**Comment by ssbarnea** [comment]
@croesnick I am afraid you need need to rebase, please don't lose hope, we are getting close. ;)

**Comment by croesnick** [comment]
@ssbarnea No worries 🙂 Hope I caught all docstrings now. Linting results look good at least.

**Comment by ssbarnea** [comment]
Ping me when conflicts are sorted and gree, I will be happy to merge it.

**Comment by croesnick** [comment]
@ssbarnea: Rebased the branch on current master & squashed the commit to get a clean history. 🙂

**Comment by ssbarnea** [comment]
@croesnick Thanks. You did great here, this was the biggest non-conformance. If you also want to address the others, you are more than welcome. One by one.

**Pull request merged**
