### PR TITLE
config: set default on missing default_context key

### PR DESCRIPTION
**Pull request by simobasso**
Closes: https://github.com/cookiecutter/cookiecutter/issues/1514
Closes: https://github.com/cookiecutter/cookiecutter/issues/1149

### CODE REVIEW

**Comment by acturner** [comment]
Does not yet fix #1513 or #1514 as far as I can tell.

**Comment by acturner** [comment]
For testing, you can clone [`cookiecutter-key-error`](https://github.com/acturner/cookiecutter-key-error) and [`cookiecutter-value-error`](https://github.com/acturner/cookiecutter-value-error) and then run:
```shell
cookiecutter cookiecutter-key-error --config-file=cookiecutter-key-error/init.yaml --no-input
```
and
```shell
cookiecutter cookiecutter-value-error --config-file=cookiecutter-value-error/init.yaml --no-input
```
respectively.

**Comment by simobasso** [comment]
@acturner thanks, just updated the description and also, I've found #1149 that seems the same issue.

**Comment by glumia** [comment]
lgtm! 

The fact you had to update both `tests/test_get_config.py::test_get_config` and `tests/test_get_user_config.py::custom_config` after editing `tests/test-config/valid-config.yaml` is a clear sign of code duplication, we should have a single fixture as source of truth of file's content.  @simobasso do you think it would be worth to open a refactor issue for that?

**Comment by simobasso** [comment]
Sure @glumia! Feel free to open an issue on this!

**Review by glumia — APPROVED** [review]

**Pull request merged**
