### PR TITLE
Address doctests D103

### LINKED ISSUE #742: Run pep257 on each file to improve docstrings
How to do this:
1. `pip install pep257`
2. Run it on a single file to see what needs to be improved: `pep257 cookiecutter/generate.py`
3. Fix as much as you can in the file. Whatever you can't fix, don't worry about fixing.
4. Submit a pull request (1 file per pull request for pep257 fixes, please)

### LINKED ISSUE #1269: PEP257 docstrings compliance
* Check first line of provided files for correct format and docstrings
* Docstrings should follow [PEP257](https://www.python.org/dev/peps/pep-0257/).  
* We use [pydocstyle](https://pypi.org/project/pydocstyle/) for validation.

Current validation log:

```
./setup.py:1 at module level:
        D100: Missing docstring in public module
./cookiecutter/zipfile.py:1 at module level:
        D100: Missing docstring in public module
./build/lib/cookiecutter/zipfile.py:1 at module level:
        D100: Missing docstring in public module
./tests/__init__.py:1 at module level:
        D104: Missing docstring in public package
./tests/test-extensions/custom-extension-pre/hooks/pre_gen_project.py:1 at module level:
        D100: Missing docstring in public module
./tests/test-extensions/hello_extension/__init__.py:1 at module level:
        D104: Missing docstring in public package
./tests/test-extensions/custom-extension-post/hooks/post_gen_project.py:1 at module level:
        D100: Missing docstring in public module
./tests/test-pyhooks/hooks/pre_gen_project.py:1 at module level:
        D100: Missing docstring in public module
./tests/test-pyhooks/hooks/post_gen_project.py:1 at module level:
        D100: Missing docstring in public module
./tests/test-output-folder/{{cookiecutter.test_name}}/{{cookiecutter.folder_name}}/{{cookiecutter.filename}}.py:1 at module level:
        D100: Missing docstring in public module
./tests/undefined-variable/dir-name/{{cookiecutter.project_slug}}/{{cookiecutter.foobar}}/helloworld.py:1 at module level:
        D100: Missing docstring in public module
./tests/test-pyshellhooks/hooks/pre_gen_project.py:1 at module level:
        D100: Missing docstring in public module
./tests/test-pyshellhooks/hooks/post_gen_project.py:1 at module level:
        D100: Missing docstring in public module
```

Subtask for #742

### PR DESCRIPTION
**Pull request by insspb**
Closes #1269 
Closes #742 

Feel free to check my english, while it is in wip.

### CODE REVIEW

**Comment by ssbarnea** [comment]
I think that you want  to remove `D103` exclude from `setup.cfg` with this change.

**Comment by insspb** [comment]
> I think that you want to remove `D103` exclude from `setup.cfg` with this change.

Want, but when will fixx all 100+ issues.

**Comment by insspb** [comment]
This PR is splited to:

#1369
#1370
#1371
#1372
#1373
#1374
#1375
#1376
#1377
#1378
#1379
#1380

**Comment by insspb** [comment]
Please do not touch branch, until other merged.

**Pull request closed without merging**
