### PR TITLE
Added debug messages for get_user_config

### PR DESCRIPTION
**Pull request by ssbarnea**
Fixes: #1306

### CODE REVIEW

**Comment by con-f-use** [comment]
While you are added, could you do this change as well:

https://github.com/cookiecutter/cookiecutter/pull/1340/commits/55a342a891ea0ee45b6c9d05a9fde4e494ad60ce

**Comment by ssbarnea** [comment]
@con-f-use Your change is good but is unrelated, should go in separated PR.

**Comment by insspb** [comment]
> While you are added, could you do this change as well:
> 
> [55a342a](https://github.com/cookiecutter/cookiecutter/commit/55a342a891ea0ee45b6c9d05a9fde4e494ad60ce)

@con-f-use I have this change in current work (#1354)

**Comment by insspb** [comment]
@ssbarnea cannot push tou your branches. You changes updated and merged in #1358

**Pull request closed without merging**
