### PR TITLE
ENH: Python module as hooks

### PR DESCRIPTION
**Pull request by 0x0L**
Thanks for this project!

This PR deals with #851. Pre and post python hooks become modules that implement the `hook` functions.

Add a file named `python_gen_project.py` in the `hooks/` directory containing

```python
def pre_gen_project(project_dir, context):
    context['some_key'] = 'abc'

def post_gen_project(project_dir, context):
    pass
```

`some_key` will be available while templating files

### CODE REVIEW

**Comment by 0x0L** [comment]
Alternatively I also implemented a version that `json.loads()` stdout of scripts and merge it into `context['cookiecutter']`.

**Comment by glenfant** [comment]
Is there a chance we have such pre/post-render hooks that can change the context one of these days. I'll work around this with custom markup placeholders that are replaced in post_gen_project.py by my own computed text (including user name, actual date, computed paths, ...). It's dirty, noisy and slow but it works.

**Comment by 0x0L** [comment]
ping @audreyr @hackebrot

The CI looks broken `ERROR: arrow requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.6`

**Comment by 0x0L** [comment]
Could be done through extensions.

**Pull request closed without merging**
