### PR TITLE
Give access to Jinja2 environment variables

### LINKED ISSUE #704: Jinja2 environment settings
Would it be possible to pass arguments to the underlying Jinja2 environment? I would like to activate the `lstrip_blocks` setting in the Jinja2 environment for more convenient whitespace trimming around code blocks. More about the Jinja API here: [Jinja2 API](http://jinja.pocoo.org/docs/dev/api/)

### PR DESCRIPTION
**Pull request by ramnes**
See the rationale behind this PR: https://github.com/audreyr/cookiecutter/issues/637#issuecomment-262207477

This PR fixes #704.

### CODE REVIEW

**Comment by ramnes** [comment]
@hackebrot gentle ping on that one also. :wink:

**Comment by ramnes** [comment]
@hackebrot @pydanny yearly ping

**Comment by ramnes** [comment]
@hackebrot I've finally updated this PR so that it is just as we discussed at the EuroPython last year! It should be simpler to review that way, I hope you'll find a few minutes for this. :pray:

**Comment by con-f-use** [comment]
Yearly ping again.

**Comment by insspb** [comment]
@con-f-use Yarly ping. haha :)

**Comment by insspb** [comment]
Hi @ramnes, @con-f-use 
Thank you for contribution. 
Unfortunately I have no access to original branch, so I restored it in PR #1419 
This branch is closed as outdated.
Feature will be merged to master soon, and expected to be in cookiecutter 2.0

**Comment by srchulo** [comment]
@insspb thanks for doing this! Do you know if 2.0 will be released soon? I would really love to use this to change `variable_start_string` and `variable_end_string`.

**Pull request closed without merging**
