### PR TITLE
fixes #348 - misspelled github shortcut traceback...

### LINKED ISSUE #348: misspelled github shortcut crashes
trying [github shortcuts](http://cookiecutter.readthedocs.org/en/latest/usage.html#works-directly-with-git-and-hg-mercurial-repos-too) with a typo produced a traceback.   For example,

```
$ cookiecutter gh:audreyr/cookiecutter-pypackage.git
$ # or:
$ cookiecutter gh:aureyr/cookiecutter-pypackage
```

generates this:

```
$ cookiecutter gh:aureyr/cookiecutter-pypackage.git
Cloning into 'cookiecutter-pypackage.git'...
Username for 'https://github.com': yarko
Password for 'https://yarko@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/aureyr/cookiecutter-pypackage.git.git/' not found
Traceback (most recent call last):
  File "/Users/yak007/workspace/cookiecutter/env/cookiecutter/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==0.8.0', 'console_scripts', 'cookiecutter')()
  File "/Users/yak007/workspace/cookiecutter/env/cookiecutter/lib/python2.7/site-packages/cookiecutter/main.py", line 169, in main
    cookiecutter(args.input_dir, args.checkout, args.no_input)
  File "/Users/yak007/workspace/cookiecutter/env/cookiecutter/lib/python2.7/site-packages/cookiecutter/main.py", line 82, in cookiecutter
    no_input=no_input
  File "/Users/yak007/workspace/cookiecutter/env/cookiecutter/lib/python2.7/site-packages/cookiecutter/vcs.py", line 108, in clone
    subprocess.check_call([repo_type, 'clone', repo_url], cwd=clone_to_dir)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'git', u'clone', u'https://github.com/autreyr/cookiecutter-pypackage.git.git']' returned non-zero exit status 128
```

... which seems a bit much just for a simple typo.

I played around with a first-draft fix, which no doubt people would do differently - but it illustrates the issue. PR #349

### PR DESCRIPTION
**Pull request by yarko**
In reference to Issue #348 

This is a first-draft, playing around (not a final fix - more of a debug instrumented experiment).

It doesn't seem to be in the coding style of the repo, but it does capture some parts of my playing around, in the comments - so I hope it will prove useful.

Right as it stands, if you use this, you get:

```
$ cookiecutter gh:aureyr/cookiecutter-pypackage.git
Username for 'https://github.com': yarko
Password for 'https://yarko@github.com': 
Error: the following failed (returned 128):
  git clone https://github.com/aureyr/cookiecutter-pypackage.git.git
```

which is a little more informative (not as noisy, no traceback).
I ended up leaving the `e.output` off, since it (at least for github) did not seem additionally useful,
always showing something about "user" regardless of where the typo was situated.

Comments?

### CODE REVIEW

**Comment by audreyr** [comment]
Sorry so late on this. I think it's a good idea, seems more user-friendly.

**Comment by hackebrot** [comment]
Any updates?

**Comment by theodesp** [comment]
@yarko I think you need to fix the conflicts here

**Comment by ssbarnea** [comment]
Closing as it appears abadoned.

**Pull request closed without merging**
