### PR TITLE
Added: Dependent questions support in JSON

### PR DESCRIPTION
**Pull request by liortct**
Addresses #1761.

Added support for dependent questions.

### CODE REVIEW

**Comment by liortct** [comment]
Hi!
We started working on a new community fork of the Cookiecutter project, named Cookieninja.
The fork is found at: https://github.com/cookieninja-generator/cookieninja

We have re-opened and merged your PR in the Cookieninja project at https://github.com/cookieninja-generator/cookieninja/pull/26

We're trying to bring the life back to this amazing project.
We are committed to reviewing and merging each PR in up to 2 weeks from the day it's opened (if there are no issues with it).
We'd really like you to join the fork, star it and contribute to it!

Thank you :)

**Comment by Guillem96** [comment]
@ericof are you planning to merge this anytime soon?

**Comment by kurtmckee** [comment]
I like this idea but am leery of this implementation. It introduces syntax in the key name that must be interpreted. I think that a different implementation may be clearer, and allow for more than boolean dependencies.

For example:

```json
{
    "trim-level": ["basic", "standard", "high-end"],
    "stereo": [
        {"case": {"trim-level": "high-end"}, "value": "xm-enabled"},
        {"case": {"trim-level": "standard"}, "prompt": ["am-fm-only", "xm-enabled"]},
        {"default": "am-fm-only"}
    ]
}
```

I'm not proposing that this is what an implementation _should_ look like, only that the ability to ask follow-up questions is useful but should be considered in the context of more conditional control over the prompting.

Due to the age of this PR, I'm closing this.

**Comment by kurtmckee** [comment]
Hi @liortct!

I recommend pinging @ericof / @pydanny / @jensens in #1761 to hash out the implementation. As noted above, I think that dependent questions will be valuable, but it will be good to discuss a solution that allows for more than boolean conditions.

**Comment by ericof** [comment]
Hello @liortct, it would be awesome to have support for dependent questions, but I do agree with @kurtmckee about discussing the proper format to implement that.
Right now, I suggest we move back to #1761 and discuss it there.

**Pull request closed without merging**
