### PR TITLE
Support nested config files

### PR DESCRIPTION
**Pull request by dariocurr**
If you wish to create a hierarchy of templates and use cookiecutter to choose among them,
you need just to specify the key ``template`` in the main configuration file to reach 
the other ones.

Let's imagine to have the following structure:

```
main-directory/
├── project-1
│   ├── cookiecutter.json
│   ├── {{cookiecutter.project_slug}}
|	│   ├── ...
├── project-2
│   ├── cookiecutter.json
│   ├── {{cookiecutter.project_slug}}
|	│   ├── ...
└── cookiecutter.json
```

It is possible to specify in the main ``cookiecutter.json`` how to reach the other 
config files as follows:
```json
{
    "template": [
	"Project 1 (./project-1)",
	"Project 2 (./project-2)"
    ]
}
```

Then, when ``cookiecutter`` is launched in the main directory it will ask to choice
among the possible templates:

```
Select template:
1 - Project 1 (./project-1)
2 - Project 2 (./project-2)
Choose from 1, 2 [1]:
```

Once a template is chosen, for example ``1``, it will continue to ask the info required by 
``cookiecutter.json`` in the ``project-1`` folder, such as ``project-slug``

### CODE REVIEW

**Comment by drkeoni** [comment]
FWIW my organization would use this if this MR can be merged in.

**Comment by dariocurr** [comment]
> FWIW my organization would use this if this MR can be merged in.

Seems like no one cares

**Comment by liortct** [comment]
@dariocurr , @drkeoni 
Hi!
We started working on a new community fork of the Cookiecutter project, named Cookieninja.
The fork is found at: https://github.com/cookieninja-generator/cookieninja

We have re-opened and merged your PR in the Cookieninja project at https://github.com/cookieninja-generator/cookieninja/pull/17

We're trying to bring the life back to this amazing project.
We are committed to reviewing and merging each PR in up to 2 weeks from the day it's opened (if there are no issues with it).
We'd really like you to join the fork, star it and contribute to it!

Thank you :)

**Review by ericof — APPROVED** [review]
Thank you, @dariocurr, and sorry for the long time it took us to review your PR.

**Comment by mhsmith** [comment]
This was a breaking change for users who already used the `template` key for something else (https://github.com/beeware/briefcase/issues/1347), but it was not released with a major version number increment.

Perhaps it would be better for special keywords to be prefixed with `cookiecutter_` to avoid clashes.

**Pull request merged**
