### PR TITLE
Added: --replay-file cli option, for replay file distributing

### PR DESCRIPTION
**Pull request by Cadair**
This adds an option to `main.cookiecutter` and the CLI to specify a json file to read the replay data from.

The motivation for this is to provide a way to run the same replay over different machines, i.e. store the replay in a git repo.

### CODE REVIEW

**Comment by epcim** [comment]
+1

**Comment by hackebrot** [comment]
Hi @Cadair! 👋 

Thank you for your contribution. I'm not sure if this approach is better than using ``--no-input`` and some custom tooling to populate extra context.

Happy to merge this with tests and docs, if others are OK with this approach.

Ping @audreyr @pydanny @michaeljoseph

**Comment by diegoholiveira** [comment]
What's the situation about this idea? Currently, I'm looking for a way to apply a template over and over again through multiple projects, so this new option to specify a replay file will be awesome to me.

There is anything that I can do to help merging this?

**Comment by Cadair** [comment]
I have not had a chance to get back to the project that this was a part of. I will try and get to it soon.

If you want to speed it up, writing tests and docs for the change in this PR is what needs doing. I will happily merge PRs against my fork with any contributions.

**Comment by browniebroke** [comment]
I"m also interested in getting this new option, I think it could help maintainers of templates with several options to reproduce issues. I will try to add the missing parts...

**Comment by salotz** [comment]
I'm very +1 for this feature, seems like a big hole in cookiecutter functionality. Any possibility of merging any time soon? What's missing?

@hackebrot 
> I'm not sure if this approach is better than using `--no-input` and some custom tooling to populate extra context.

The proposed option is very non-intuitive. This issue is by far the least-surprise approach. Cookiecutter already accepts JSON files for the defaults. Like others have said this would simplify testing immensely.

I might suggest also adding an option to generate a `.cookiecutter_replay` inside of generated repos rather than some user-configured location as well. But thats another story.

**Comment by insspb** [comment]
@Cadair @browniebroke 
Thank you for contribution and sorry us for long delay with answer. 
This feature is merged to master branch and will be released with `cookiecutter 2.0`
At this time you can use it from installing from master directly.

@diegoholiveira @epcim 
This feature is merged to master branch and will be released with `cookiecutter 2.0`
At this time you can use it from installing from master directly.

**Comment by salotz** [comment]
Awesome thank you for this!

**Comment by insspb** [comment]
@salotz You are welcome.

**Pull request merged**
