### PR TITLE
Add support for symlinks in cookiecutter templates

### PR DESCRIPTION
**Pull request by pjbull**
- Support copying symlinks as symlinks for both rendered and
non-rendered directories
 - Support symlinks that link to a rendered directory
 - Support symlinks that get rendered

### CODE REVIEW

**Comment by pjbull** [comment]
This PR aims to tackle #865

**Comment by pjbull** [comment]
Sorry for the noise here--don't have a Windows+Python 2.7 environment, so was letting AppVeyor test things for me.

This fix generally works, but there is a complication: Windows+Python2.7 doesn't support symlinks out of the box. To make this work, I've added the `win_utils.py` file which pulls together a bunch of kernel32 functions to enable symlinks. It looks to me like there's one package on PyPI that would enable this similar functions [jaraco.windows](https://github.com/jaraco/jaraco.windows) if the preference is to take an external dependency on this pacakge in the Windows+Python2.7 case.

I have a little work left to re-implement rmtree in a way that supports symlinks in Windows in the tests. Also, letting flake8 fail on the win_utils.py until we settle whether to use those versions of take the `jaraco.windows` dependency.

**Comment by pjbull** [comment]
Finally got a Windows VM to develop against so could get symlinks working there. Separated out the posix and the Windows changes into separate commits so we can reason about them separately.

For background, most concise summary of symlinks in Windows and Python <3.2 is here:
 - http://stackoverflow.com/a/15259028/1692709
 - I have a [separate branch taking a dependency on `jaraco.windows` instead of rolling our own functions](https://github.com/pjbull/cookiecutter/tree/win-symlink-jaraco), but still have some failing tests when running `rmtree` on a dir with symbolic links.

**Comment by bittner** [comment]
Can we merge this PR?

I understand it's a bit large, mainly due to adding symlink support for Windows. If this is a problem can we get the PR merged earlier if we move the Windows-related changes to a separate PR?

**Comment by hackebrot** [comment]
@pjbull @bittner I'm not really confident merging and maintaining this. It adds a lot of complexity and it's hard for me to test as I don't usually use windows.

I don't object merging this, but we need someone with windows expertise to review this.

**Comment by bittner** [comment]
Frankly, symlinks on Windows feels rather artificial to me. I wouldn't know how to create them using the file manager. Do we really have a issue with symbolic links on Windows? If we have cookiecutters (templates) that have symbolic links (e.g. created on Unix OSes) under version control, do they have a meaning under Windows?

@hackebrot If the complexity that Windows introduces were removed in this PR would you be willing to merge this PR right away?

**Comment by bittner** [comment]
@hackebrot Should the complexity of Windows be removed from this PR to make the decision of merging easier?

**Comment by pjbull** [comment]
Added just the PR for posix systems and newer Python, which is cleaner. I'll create an issue for Windows with Python < 3.2, which we may end up won't fixing given the complexity it introduces.

**Comment by insspb** [comment]
@pjbull, unfortunately, it was not reviewed in time. Currently, we are making cookiecooter issues and prs cleanup after some time without project maintenance. If you can adapt this code to currentl project code state it will be reviewed much faster again.

**Comment by insspb** [comment]
@ssbarnea Please stop closing pull requests without any resolution. At least for problematic functions like symlinks. 

It is hard to find them again. And this problem not yet solved.

**Pull request closed without merging**
