### PR TITLE
update AUTHOR lead

### PR DESCRIPTION
**Pull request by HosamAlmoghraby**
audreyr has moved to audreyfeldroy
check it out here please: https://github.com/audreyr

### CODE REVIEW

**Comment by glumia** [comment]
lgtm!

By the way I think this file is severly outdated, Github reports 234 contributors but there are listed only 139 in it. I'm opening another issue to address it.

**Comment by HosamAlmoghraby** [comment]
I have updated Daniel Feldroy's name in the AUTHORS page, and also I went through the README page and updated Audrey's github link.

**Review by simobasso — APPROVED** [review]

**Comment by HosamAlmoghraby** [comment]
Hello,

I have been looking for a solution to automate the process of adding new contributors to the AUTHORS page and keeping that page up to date using some automation tools. I came to a tool called **[allcontributors](https://allcontributors.org/)**

The way  how the tool works:
1. Install the Bot to the project

2. Start a pull request or comment
3. Mention the @all-contributors Bot
4. Add a contributor’s username and contribution type

5. Post and our ReadMe (Authors in our case) updates automatically!

How can I know if there is an interest to discuss that?

Best Regards
Hosam

**Comment by HosamAlmoghraby** [comment]
CC: @audreyfeldroy @pydanny

Thanks

**Pull request merged**
