### PR TITLE
Use yaml optionally

### PR DESCRIPTION
**Pull request by umeboshi2**
This PR addresses #970.
If a ```cookiecutter.yml``` is present and a ```cookiecutter.json``` file is absent, it will read the config from the yaml file.  If the json file is present, it will be used for config even if the yaml file exists.  AFAICT, the only foreseeable problem with this PR is that pyyaml is inluded in the requirements in ```setup.py```.  If you can accept an "optional requirements" file, I can move the dependency to that and add instructions in the readme.  Except for the requirement being listed, I have tried to make this feature as optional as possible.  There is also an ```import yaml``` statement in ```generate.py`` ` that can be placed in a "try except" statement if desired.

I have been using this branch for the last year successfully and just rebased from current master before making this PR.  All of the templates that I have created are using yaml for config and they have been working just fine.

### CODE REVIEW

**Comment by pydanny** [comment]
The problem with this PR is that it's reliant on PyYAML. As of a few years ago, PyYAML could not be reliably installed on all platforms, something that is an absolute requirement for Cookiecutter. This is what predicated the creation of Poyo, a simple and pure python YAML parser.

If the installation issues for PyYAML on windows have been resolved, then we can consider this PR.

**Comment by ssbarnea** [comment]
@pydanny PyYAML had a period where it lacked maintenance and that is why runamel was also created but those times are now gone. Considering https://github.com/hackebrot/poyo/issues/23 I am inclined to support more the use of pyyaml as is more mature.

Pure Python is a benefit but only when both projects are actively maintained. If we are to count popularity I would say that Pyyam is about 8x more popular.

Lets see if there are any installation issues on Windows with pyyaml.

**Comment by insspb** [comment]
Hi @umeboshi2  and thank you for contribution. 
it will be greate to include it in nearest cookiecutter release, as it will be major refactoring.
Can you do three things with it:

1. Rebase to current master
2. Write documentation example with template in yaml. 
3. Write some tests.

**Comment by ssbarnea** [comment]
@umeboshi2 Yep, keep it fresh and it will happen very soon. Many things changed with cookiecutter maintenance since you originally raised it.

**Review by lastthyme — APPROVED** [review]

**Comment by kurtmckee** [comment]
I'm closing this PR due to its age.

**Pull request closed without merging**
