### PR TITLE
add cookiecutter-flask-devops link

### PR DESCRIPTION
**Pull request by Colaplusice**
i create a cookiecutter template for flask with below features:
- peewee orm and simple migration
- pytest for unit test and black flake8 for code format
- html5-boilerplate for jinjia template
- docker-compose to deploy 
- gitlab-ci for auto update code for vps (WIP)
- per-commit for source control

### CODE REVIEW

**Comment by insspb** [comment]
Local tox test with merged #1181:
```text
___________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________
  py27: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  py37: commands succeeded
ERROR:   pypy: InterpreterNotFound: pypy
  flake8: commands succeeded
```

Merge required to start #1179

**Comment by michaeljoseph** [comment]
@ssbarnea @insspb are you folks following https://github.com/cookiecutter/cookiecutter/blob/master/docs/core_committer_guide.rst#process-accepting-template-pull-requests when approving cookiecutters? (mainly checking that you're _actually_ generating projects with the candidate templates)

**Comment by ssbarnea** [comment]
@michaeljoseph Nope, just did a visual inspection that it points to what it looks as a valid template. 
Now considering that we do not have CI for this I wonder if it would not be better to completly remove remove the list of templates and replace it with a github link to https://github.com/topics/cookiecutter-template

Any template author could use this topic on his project, making it visible and github "social" features will take care of the rest. This way we woud outsource this never-ending source of PRs.

Also, even if a template generates a project, it does not mean that is usable or not even malicious. Thus I propose to scrap that section completely.

@pydanny What do you think about that? There are already 134 repositories using this topic.

**Comment by michaeljoseph** [comment]
I'm 👍 on moving cookiecutters out of the README to reduce the maintenance load.
( 👀 #296)

**Comment by ssbarnea** [comment]
We are no longer maintaining a list of templates inside README file and instead we use github topics feature. Please read https://github.com/cookiecutter/cookiecutter#a-pantry-full-of-cookiecutters and add the needed topics to your repository and people will be able to find your template. The most important one is ``cookiecutter-template``.

We are also going to remove most of already listed templates from there, in order not avoid being biased.

**Pull request closed without merging**
