### PR TITLE
Add tiangolo/full-stack and tiangolo/full-stack-flask-couchdb

### PR DESCRIPTION
**Pull request by tiangolo**
I'm adding links to two full stack project generators I created with Cookiecutter :smile:

They include Docker, Flask, Celery, automatic HTTPS with Traefik, Docker based testing, and a bunch of other features. One is based on PostgreSQL and the other on CouchDB. 

They are being actively used in the company I work for and the previous one too.

### CODE REVIEW

**Comment by tiangolo** [comment]
I'm seeing errors that I understand are not related to the docs changes. What should I do?

**Comment by insspb** [comment]
@tiangolo Everything fine, keep it going. I will mark it as reviewed after local test.

**Comment by ssbarnea** [comment]
We are no longer maintaining a list of templates inside README file and instead we use github topics feature. Please read https://github.com/cookiecutter/cookiecutter#a-pantry-full-of-cookiecutters and add the needed topics to your repository and people will be able to find your template. The most important one is ``cookiecutter-template``.

We are also going to remove most of already listed templates from there, in order not avoid being biased.

**Comment by tiangolo** [comment]
Good idea, I'll check it to update the topics. Thanks!

**Pull request closed without merging**
