### PR TITLE
Adopt setuptools-scm packaging

### PR DESCRIPTION
**Pull request by ssbarnea**
One direct benefit of this change is that package version is no longer hardcoded and is generated based on last tag.

Related: #1555

### CODE REVIEW

**Comment by luzfcb** [comment]
The only thing I don't like about `setuptools_scm` is that apparently, it doesn't work well with PEP 508

package@https://github.com/repository/project/archive/branch_or_commit_hash.zip#sha1=HASH

I discovered this behavior yesterday so I don't have a solution or workaround

```bash
pip install pip -U
pip django-user-sessions@https://github.com/jazzband/django-user-sessions/archive/master.zip
```

**Comment by ssbarnea** [comment]
It is expected not to work with git archives because it does not have any clue about which version to use. Git clones work. Is not the only thing not working with git archives. If I remember well microsoft was considering adding some extra metadata to these archives in order to enable consumers to make use of tag information.

**Review by simobasso — COMMENTED** [review]
Hey @ssbarnea 👋 ,

Does this configuration get only the last tag? What about backports?

**Comment by ssbarnea** [comment]
In fact it will work for backports as long they are made from inside branches named stable/*

**Review by simobasso — APPROVED** [review]

**Comment by audreyfeldroy** [comment]
Hi @simobasso @ssbarnea @luzfcb it looks like you have done a huge amount of work on attempting to improve packaging of Cookiecutter. The current team that is trying to put out the Cookiecutter 2 release (including myself) is having trouble getting setuptools_scm and build to work properly. We want to use the improved setup that you created here in this pull request, but we just cant get it to work on my computer. Can any of you help us sometime over the next 24 hours over a voice screen share in discord the Cookiecutter [Discord](https://discord.gg/ZvaJt9cAbj)? The ideal situation would be for us to use the current setup as-is to the new release, but if we cant figure it out, we will revert this pull request.

NOTE: This message was typed by @ozer550  as Audrey is unable to use her hands.

**Pull request merged**
