### PR TITLE
Changed: Generated projects can use multiple type hooks at same time. (sh + py)

### PR DESCRIPTION
**Pull request by milonimrod**
I've added support for multiple hook types in the same project (both _sh_ and _py_)
#973

### CODE REVIEW

**Comment by theodesp** [comment]
Looks good. I would expect more tests though that cover this case.

**Comment by milonimrod** [comment]
@theodesp  - as requested, I added a test

**Comment by theodesp** [comment]
@milonimrod Good Just PM the Team in Gitter for the updates https://gitter.im/audreyr/cookiecutter

**Comment by jaklan** [comment]
@theodesp 2 years later, why it's still not merged? It's already done, it's so trivial, but really, really useful, but still it's not available in master...

**Pull request merged**
