### PR TITLE
Documentation overhaul

### LINKED ISSUE #721: Consider splitting features of cookiecutter in README
After talking with folks at PyCon and the sprints, some folks just wish to consume cookiecutter templates while others have the interest in creating templates.

It might be helpful to break the features into two subsections.

### LINKED ISSUE #1411: Documentation 2.0: All tutorials should be combined to one menu
All tutorials should be combined to one menu

### PR DESCRIPTION
**Pull request by jensens**
- fixes #721 
- addresses https://github.com/BruceEckel/HelloCookieCutter1/issues/8 (removes submodule and links to repository)
- fixes #1411 (parts taken from stalled #1423)
- addresses #1413 (moves cli docs to top level)
- addresses #1613
- Remove debian installation instructions (part of #1409)
- fixes some Sphinx warnings
- doc style: one line per sentence (not everywhere yet). Hint: in case anyone wants to translate the docs in future.
- README indent and heading level fixes.
- several minor fixes.

### CODE REVIEW

**Review by ericof — APPROVED** [review]
LGTM

**Comment by insspb** [comment]
@jensens thank you for contribution, but please do not do this in future: 

> doc style: one line per sentence (not everywhere yet). Hint: in case anyone wants to translate the docs in future.

Documentation translate make any project less maintainable (if it is not something with huge use), but such changes makes documentation in files harder to read.

@ericof Please consider my note in future documentation merges.

**Comment by jensens** [comment]
Documentation is not code, we did large documenation in the past with real experts on the topic. One sentence per line is the standard. So we should stick to it.

**Comment by insspb** [comment]
@jensens i do not remember any translation attempts. We do not have complete documentation in english. Nothing to say about other languages. But I remember moving to markdown #1216, and this will be done in future for most not auto-generated modules, as Myst support for rst is very elegant too.

About docs not a code. Docs for end users is much more required, but to develop a doc you need to look inside.
But did you tried to read 231 characters string on small screen? try, it will be fun.

Check pre-commit file history to find out how rst checks was set up in past. (2020) also check history of setup.cfg.

As for side effects etc... I cannot agree with it. 

As is standart, For subtitles and things like that for sure. For docs? I see it first time. I do not know any maintainer, who want to watch and work with doc translation.

**Pull request merged**
