### PR TITLE
Convert RST files in docs/advanced to Markdown

### PR DESCRIPTION
**Pull request by sasili-adetunji**
Referencing issue [1179](https://github.com/cookiecutter/cookiecutter/issues/1179)

I converted all `rst` files in `docs/advanced`

### CODE REVIEW

**Comment by michaeljoseph** [comment]
@sasili-adetunji looks like your build is failing our `pre-commit` trailing whitespace check: https://travis-ci.com/cookiecutter/cookiecutter/jobs/224115003

**Comment by michaeljoseph** [comment]
@sasili-adetunji https://travis-ci.com/cookiecutter/cookiecutter/jobs/224129085 is complaining about `docs/usage.rst` for some reason.
I think the best way to address this would be to run the `tox -e lint` task locally?

**Comment by michaeljoseph** [comment]
Also, I think may be ok to put the new markdown files in the same directory as the rst ones?

**Comment by insspb** [comment]
this is sphinx documents, rendered only on main site. Do we really need to convert it? I am not sure that  idea was in converting all the docs. I assume, that idea was to convert docs, available on main github page. 
But let's hear from other devs.

**Comment by insspb** [comment]
@sasili-adetunji 
After fresh review. This PR added another directory, that will not be rendered by sphinx. 
And there will be files duplication in sphinx and MD. 
The basic task was phrased wrong, and I do not think that we need conversion of all docs to md.
So this will not be merged. Sorry.

**Pull request closed without merging**
