### PR TITLE
Detect the original file newline style and apply it to rendered template

### PR DESCRIPTION
**Pull request by franciscomoma**
Hello! I've seen that this [issue](https://github.com/audreyr/cookiecutter/issues/405) was still open, and I decided to fix it detecting the original file ending style and applying it to the rendered new file.

I've also added a .gitattributes file to set CRLF to files that ends with *crlf.txt.

### CODE REVIEW

**Comment by dchimeno** [comment]
This solves my problem with Windows, any way this could be merge?

**Comment by tiangolo** [comment]
I think this is bitting several Windows users for some of the Cookiecutter project generators I have: https://github.com/tiangolo/full-stack-fastapi-couchbase/issues/8, https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/13

I guess this is probably bitting many more users of other Cookiecutters.

Is there a chance a maintainer can take a look at this PR? Is there any help we can provide?

**Comment by Hickstone** [comment]
We are also affected by this. This would solve many problems with generated unix files on windows.

**Comment by insspb** [comment]
@franciscomoma 
Thank you for contribution. 

Merged to #1407 
Will be in 2.0

**Comment by franciscomoma** [comment]
> @franciscomoma
> Thank you for contribution.
> 
> Merged to #1407
> Will be in 2.0

Thank you so much!

**Pull request closed without merging**
