### PR TITLE
cleanup files if panics during hooks - bugfix

### PR DESCRIPTION
**Pull request by liortct**
Addresses #1754.

Fixed bug where files aren't cleaned up during panics, by adding an additional exception catch.

### CODE REVIEW

**Comment by liortct** [comment]
Hi!
We started working on a new community fork of the Cookiecutter project, named Cookieninja.
The fork is found at: https://github.com/cookieninja-generator/cookieninja

We have re-opened and merged your PR in the Cookieninja project at https://github.com/cookieninja-generator/cookieninja/pull/30

We're trying to bring the life back to this amazing project.
We are committed to reviewing and merging each PR in up to 2 weeks from the day it's opened (if there are no issues with it).
We'd really like you to join the fork, star it and contribute to it!

Thank you :)

**Review by kurtmckee — APPROVED** [review]
@jensens @ericof @browniebroke Please merge this PR.

It appears to resolve an existing bug.

**Comment by browniebroke** [comment]
Please don't @ me, while I'm a member of the organisation, I'm not a maintainer of the cookiecutter CLI project.

**Comment by kurtmckee** [comment]
My apologies!! It won't happen anymore. You're correct, I was looking at members of the organization.

Please have a good weekend!

**Review by jensens — APPROVED** [review]

**Pull request merged**
