### PR TITLE
Use XDG_CACHE_HOME for caching

### PR DESCRIPTION
**Pull request by ssbarnea**
[XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defines is a single base directory relative to which user-specific non-essential (cached) data should be written. This directory is defined by the environment variable $XDG_CACHE_HOME.

This commit change directories `cookiecutter_replay` and `cookiecutters` where cookiecutter stores its own data.

### CODE REVIEW

**Comment by insspb** [comment]
Related #104

**Comment by ssbarnea** [comment]
@insspb There is a problem with python2.7 32bit from appveyor which failed twice without any explanation. When I added the `-v` to pytest to increase verbosity, it worked. 

I propose we keep the -v to see what happens in the future.

**Comment by luzfcb** [comment]
> I propose we keep the -v to see what happens in the future.

+1 to this idea.

**Comment by insspb** [comment]
@ssbarnea @luzfcb Agree with -v, about pull request, will review a little bit later.

**Comment by ssbarnea** [comment]
I removed this feature from 1.7.1 release because it is introduding a breaking change: the
new caching directory will be different.

**Comment by insspb** [comment]
* Related to #1309 
* Do not forget to mention @ligurio in project contributors.

**Comment by luzfcb** [comment]
Any manual test was made on Windows?

**Comment by ssbarnea** [comment]
@luzfcb I am not a big fun of either manual-testing or Windows platform, so you are welcomed to take this challenge. The good part is that we do hae CI/CD running on Windows, and it did not fail.

**Comment by insspb** [comment]
@ssbarnea please check #971 for same ideas, but with external windows support

**Comment by ssbarnea** [comment]
Closing as dead, I hope someone will implement it.

**Pull request closed without merging**
