### PR TITLE
shrink mypy whitelist for other modules

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by danieleades** [comment]
@jensens this is ready to go!

**Comment by danieleades** [comment]
@jensens this is ready to go!

**Review by jensens — APPROVED** [review]

**Comment by danieleades** [comment]
@jensens this has been deconflicted!

**Review by jensens — APPROVED** [review]

**Comment by jensens** [comment]
> @jensens any idea why the codecov checks aren't reporting back?
> 
> from https://app.codecov.io/github/cookiecutter/cookiecutter/commit/d6c4e97626d4fee5da66558e253ed26cc8668f6d:
> 
> > There is an error processing the coverage reports. Common issues are [files paths](https://docs.codecov.com/docs/fixing-paths), empty files or expired reports. See error [reference](https://docs.codecov.com/docs/error-reference) page for additional troubleshooting to resolve error.

no, but we had some problems when the fork was outside the main repo. I ignore this for now as long it works on main then ;)

**Pull request merged**
