### PR TITLE
Added: --list-installed cli option, listing already downloaded cookiecutter packages

### PR DESCRIPTION
**Pull request by chrisbrake**
This is a re-implementation of #916 since that seems to have died due to lack of test coverage.

Adds new command: cookiecutter --list

This lists locally available templates, for example:

user$ cookiecutter --list
7 installed templates: 
 * cookiecutter-bottle
 * cookiecutter-pyramid-talk-python-starter
 * cookiecutter-sublime-text-3-plugin
 * cookiecutter-template
 * puppet-openstack-cookiecutter
 * pyramid-cookiecutter-starter
 * python-macon-template

### CODE REVIEW

**Comment by chrisbrake** [comment]
The Travis failures do not appear to be related to my change.

> Unable to download 3.4 archive. The archive may not exist. Please consider a different version.
> Unable to download 3.5 archive. The archive may not exist. Please consider a different version.

**Comment by chrisbrake** [comment]
> Any chance of this being merged soon?

I've not heard anything from the maintainers.

**Comment by ssbarnea** [comment]
@marcosfelt can you please resolve conflicts and assure it passes CI? If green I will merge it, if not updated I will closet the PR.

**Comment by insspb** [comment]
@chrisbrake @mikeckennedy Thank you for contribution. I updated this to last codebase version and merged to master. 
It will be available in cookiecutter 2.0 or you can use it in current master. 
By the way. Please, never use same variables names like build-in defaults (was `list`).

@marcosfelt 
It will be available in cookiecutter 2.0 or you can use it in current master.

**Comment by mikeckennedy** [comment]
Very cool. Thank you.

**Pull request merged**
