### PR TITLE
fix(#1650): fix failure when overwritting directory with `_copy_without_render` in context

### LINKED ISSUE #1650: override doesn't work if you have a copy only directory
* Cookiecutter version: 1.7.3
* Template project url: https://github.com/zhongdai/issue-cookiecutter.git
* Python version: 3.7
* Operating System: Darwin Kernel Version 21.3.0

### Description:

There is an option for the `cookiecutter` command, which is called [override folder](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/cli_options.html#cmdoption-f). However, it does not work if you have defined a 'copy only directory' in your `cookiecutter.json`. I checked the code, looks like a check needs to be done before the copy in the `generate.py`. 

I am happy to fix that, and I got a running version in my local, just need to get familiar with the testing requirements and contributing rules.

### What I've run:

```
~/projects/temp
❯ cookiecutter --version
Cookiecutter 1.7.3 from /Users/zhongdai/.local/pipx/venvs/cookiecutter/lib/python3.7/site-packages (Python 3.7)

~/projects/temp
❯ uname -a
Darwin Zhongs-iMac.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

~/projects/temp
❯ cookiecutter -v https://github.com/zhongdai/issue-cookiecutter.git
DEBUG cookiecutter.config: Loading config from /Users/zhongdai/.cookiecutterrc.
DEBUG cookiecutter.config: config_path is /Users/zhongdai/.cookiecutterrc
DEBUG cookiecutter.utils: Making sure path exists: /Users/zhongdai/.cookiecutters/
DEBUG cookiecutter.vcs: repo_dir is /Users/zhongdai/.cookiecutters/issue-cookiecutter
DEBUG cookiecutter.main: context_file is /Users/zhongdai/.cookiecutters/issue-cookiecutter/cookiecutter.json
DEBUG cookiecutter.generate: Context generated is OrderedDict([('cookiecutter', OrderedDict([('project_name', 'reproduce-issue-project'), ('_copy_without_render', ['copy_only_dir'])]))])
project_name [reproduce-issue-project]:
DEBUG cookiecutter.utils: Making sure path exists: /Users/zhongdai/.cookiecutter_replay/
DEBUG cookiecutter.find: Searching /Users/zhongdai/.cookiecutters/issue-cookiecutter for the project template.
DEBUG cookiecutter.find: The project template appears to be /Users/zhongdai/.cookiecutters/issue-cookiecutter/{{cookiecutter.project_name}}
DEBUG cookiecutter.generate: Generating project from /Users/zhongdai/.cookiecutters/issue-cookiecutter/{{cookiecutter.project_name}}...
DEBUG cookiecutter.generate: Rendered dir reproduce-issue-project must exist in output_dir .
DEBUG cookiecutter.utils: Making sure path exists: reproduce-issue-project
DEBUG cookiecutter.utils: Created directory at: reproduce-issue-project
DEBUG cookiecutter.generate: Project directory is /Users/zhongdai/projects/temp/reproduce-issue-project
DEBUG cookiecutter.hooks: hooks_dir is /Users/zhongdai/.cookiecutters/issue-cookiecutter/hooks
DEBUG cookiecutter.hooks: No hooks/dir in template_dir
DEBUG cookiecutter.hooks: No pre_gen_project hook found
DEBUG cookiecutter.generate: Copying dir copy_only_dir to /Users/zhongdai/projects/temp/reproduce-issue-project/copy_only_dir without rendering
DEBUG cookiecutter.generate: Processing file hello.py
DEBUG cookiecutter.generate: Created file at /Users/zhongdai/projects/temp/reproduce-issue-project/hello.py
DEBUG cookiecutter.generate: Check hello.py to see if it's a binary
DEBUG cookiecutter.generate: Writing contents to file /Users/zhongdai/projects/temp/reproduce-issue-project/hello.py
DEBUG cookiecutter.hooks: hooks_dir is /Users/zhongdai/.cookiecutters/issue-cookiecutter/hooks
DEBUG cookiecutter.hooks: No hooks/dir in template_dir
DEBUG cookiecutter.hooks: No post_gen_project hook found

~/projects/temp
❯ cookiecutter -v -f https://github.com/zhongdai/issue-cookiecutter.git
DEBUG cookiecutter.config: Loading config from /Users/zhongdai/.cookiecutterrc.
DEBUG cookiecutter.config: config_path is /Users/zhongdai/.cookiecutterrc
DEBUG cookiecutter.utils: Making sure path exists: /Users/zhongdai/.cookiecutters/
DEBUG cookiecutter.vcs: repo_dir is /Users/zhongdai/.cookiecutters/issue-cookiecutter
You've downloaded /Users/zhongdai/.cookiecutters/issue-cookiecutter before. Is it okay to delete and re-download it? [yes]:
DEBUG cookiecutter.main: context_file is /Users/zhongdai/.cookiecutters/issue-cookiecutter/cookiecutter.json
DEBUG cookiecutter.generate: Context generated is OrderedDict([('cookiecutter', OrderedDict([('project_name', 'reproduce-issue-project'), ('_copy_without_render', ['copy_only_dir'])]))])
project_name [reproduce-issue-project]:
DEBUG cookiecutter.utils: Making sure path exists: /Users/zhongdai/.cookiecutter_replay/
DEBUG cookiecutter.find: Searching /Users/zhongdai/.cookiecutters/issue-cookiecutter for the project template.
DEBUG cookiecutter.find: The project template appears to be /Users/zhongdai/.cookiecutters/issue-cookiecutter/{{cookiecutter.project_name}}
DEBUG cookiecutter.generate: Generating project from /Users/zhongdai/.cookiecutters/issue-cookiecutter/{{cookiecutter.project_name}}...
DEBUG cookiecutter.generate: Rendered dir reproduce-issue-project must exist in output_dir .
DEBUG cookiecutter.generate: Output directory reproduce-issue-project already exists, overwriting it
DEBUG cookiecutter.generate: Project directory is /Users/zhongdai/projects/temp/reproduce-issue-project
DEBUG cookiecutter.hooks: hooks_dir is /Users/zhongdai/.cookiecutters/issue-cookiecutter/hooks
DEBUG cookiecutter.hooks: No hooks/dir in template_dir
DEBUG cookiecutter.hooks: No pre_gen_project hook found
DEBUG cookiecutter.generate: Copying dir copy_only_dir to /Users/zhongdai/projects/temp/reproduce-issue-project/copy_only_dir without rendering
Traceback (most recent call last):
  File "/Users/zhongdai/.local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/Users/zhongdai/.local/pipx/venvs/cookiecutter/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zhongdai/.local/pipx/venvs/cookiecutter/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/zhongdai/.local/pipx/venvs/cookiecutter/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zhongdai/.local/pipx/venvs/cookiecutter/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/zhongdai/.local/pipx/venvs/cookiecutter/lib/python3.7/site-packages/cookiecutter/cli.py", line 152, in main
    skip_if_file_exists=skip_if_file_exists,
  File "/Users/zhongdai/.local/pipx/venvs/cookiecutter/lib/python3.7/site-packages/cookiecutter/main.py", line 106, in cookiecutter
    output_dir=output_dir,
  File "/Users/zhongdai/.local/pipx/venvs/cookiecutter/lib/python3.7/site-packages/cookiecutter/generate.py", line 321, in generate_files
    shutil.copytree(indir, outdir)
  File "/Users/zhongdai/.pyenv/versions/3.7.11/lib/python3.7/shutil.py", line 324, in copytree
    os.makedirs(dst)
  File "/Users/zhongdai/.pyenv/versions/3.7.11/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/zhongdai/projects/temp/reproduce-issue-project/copy_only_dir'
```

### PR DESCRIPTION
**Pull request by att14**
Fixes #1650

### CODE REVIEW

**Comment by zhongdai** [comment]
I can see the problems with this fix,

- The `dirs_exist_ok` was added after Python 3.8, so it won't work for the earlier versions.
- It does not serve the purpose of the `-f` flag. If the files in the copy-only-dir have been changed, your code won't generate the new content based on the latest files in the source.

**Comment by att14** [comment]
> It does not serve the purpose of the `-f` flag. If the files in the copy-only-dir have been changed, your code won't generate the new content based on the latest files in the source.

That isn't true, it still copies the directoy in full.

```
In [1]: import shutil

In [2]: import os

In [3]: shutil.copytree('./test', './test-copy', dirs_exist_ok=True)
Out[3]: './test-copy'

In [4]: os.listdir('./test-copy')
Out[4]: ['foo.txt']

In [5]: from pathlib import Path

In [6]: Path('./test/bar.txt').touch()

In [7]: os.listdir('./test')
Out[7]: ['foo.txt', 'bar.txt']

In [8]: shutil.copytree('./test', './test-copy', dirs_exist_ok=True)
Out[8]: './test-copy'

In [9]: os.listdir('./test-copy')
Out[9]: ['foo.txt', 'bar.txt']
```

> The `dirs_exist_ok` was added after Python 3.8, so it won't work for the earlier versions.

This is probably a problem. Maybe I can combine our two solutions. Basically, need to modify your version to respect the `overwrite_if_exists` flag.

**Comment by zhongdai** [comment]
Now I got your point, and I think it depends on how we understand the flag `-f`. I am considering it is a flag to re-create the destination anyway, without keeping any changes (modification or new files). But if the flag is only for overriding if exists, my solution won't work, we should keep whatever has been updated in the destination.

**Comment by att14** [comment]
Your solution is more correct. `copytree` doesn't handle deleted files at all. I made a comment on #1651 to respect the flag, and then I think yours is the best solution.

**Pull request closed without merging**
