### PR TITLE
Convert CLI provided strings to booleans for boolean config variables

### LINKED ISSUE #1973: Cannot properly override boolean variable from command line
* Cookiecutter version: 2.4.0
* Template project url: N/A
* Python version: 3.10
* Operating System: Linux

### Description:

I tried to use the boolean variable. It works great when generating from interactive prompt. But when I try to use --no-input with command line context it doesn't propagate words like "no" or "false" as false value, but rather it seems to take it as string value, so if I pass an empty string it will be evaluated to false.

Here is my cookiecutter.json:
```json
{
  "project_name": "test_boolean",
  "generate_text": true
}
```

I have a file with template:
```
{% if cookiecutter.generate_text %}
Hello, world!
{% endif %}
```

If I run `cookiecutter --no-input -f . generate_text=false`, the generated file still has the "Hello, world!". But if i use `generate_text=""` the generated file will be empty.

### PR DESCRIPTION
**Pull request by tylermilner**
Fixes #1973 - a bug where the override value provided via command line wasn't being properly converted to its boolean counterpart.

Since override values from the command line are interpreted as strings, we need to convert the override value to a boolean if it's overriding a boolean variable.

I'm a total Python newbie so please let me know if there's anything I can change to make this better.

### CODE REVIEW

**Review by jensens — APPROVED** [review]

**Comment by jensens** [comment]
Thanks!

**Comment by jaap3** [comment]
Would love a release with this fix. Just noticed our CI is not actually testing what I thought it was because of this issue

**Comment by jensens** [comment]
You are right, it is time for a release. I'll put it on my todo list for the next days! Thanks for the reminder!

**Comment by jaap3** [comment]
@jensens thanks! Was able to work around it with a pre-generate hook, so no rush 😉

**Comment by scprek** [comment]
Looks like 2.6.0 was in February, this to me seems like a fix release? What's the hold up here?

**Pull request merged**
