### PR TITLE
[WIP][add] ability to override render context before rendering.

### PR DESCRIPTION
**Pull request by simahawk**
A common requirement - at least in our projects - is to generate new variables on the fly based on user input.
Now you can use `get_render_context` to generate the context and manipulate it before passing it to cookiecutter.
Example:
```
from cookiecutter.main import cookiecutter, get_render_context
from cookiecutter.config import get_user_config

config_dict = get_user_config()
context_file = os.path.join(template_path, 'cookiecutter.json')
# this triggers questions prompt
render_context = get_render_context(context_file, config_dict)
render_context['cookiecutter']['whatever_you_want_to_render'] = 'oh yeah!'
cookiecutter(template_path, render_context=render_context)
```
TODO: update tests and docs.

### CODE REVIEW

**Comment by ericof** [comment]
@simahawk Do you a use case for that? (If it is the same as mine we could join forces)

**Comment by simahawk** [comment]
@ericof hey pal :) Use case is mostly the one described in the description :stuck_out_tongue_winking_eye:  You want to play with variables at runtime based on user input. 

For instance, we use it to generate our cloud platform project settings by computing secure passwords, random database names,  memory size, workers number, etc.

Is not published but I can give you a private picture of it if you need it :wink:

**Comment by ericof** [comment]
@simahawk I have the same user case on Websauna, so let's work together on this.
It seems you need the tests and docs, correct?

**Comment by simahawk** [comment]
@ericof that would be awesome :)

**Comment by ssbarnea** [comment]
This is far too old, please reopen after rebasing if still desired.

**Pull request closed without merging**
