### PR TITLE
New 2.0 Context Implementation

### PR DESCRIPTION
**Pull request by eruber**
For your consideration - an implementation of version 2 context format as specified by [hackebrot's pull request 848](https://github.com/audreyr/cookiecutter/pull/848) and using hackebrot's context.py module from [his new context format branch here](https://github.com/hackebrot/cookiecutter/tree/new-context-format).

My detailed dev notes on the implementation are [available here](http://cookiecutter-v2-fork-docs.readthedocs.io/en/latest/index.html) along with [Travis](https://www.travis-ci.org/eruber/cookiecutter) and [AppVeyor](https://ci.appveyor.com/project/eruber/cookiecutter) reports. The [dev notes](http://cookiecutter-v2-fork-docs.readthedocs.io/en/latest/index.html) cover implementation goals, implementation details, and testing.

The high-altitude summary is - one new file added, two existing files modified, and created 48 new tests for code coverage. Currently not passing Python 2.7, but 3.3 - 3.6 are green. I might need help with 2.7. Assuming of course, this pull request gains traction.

Added a [ReadTheDocs](http://cookiecutter-version-2-template-format.readthedocs.io/en/latest/index.html) project that documents the version 2 Cookiecutter template format that this rull requests supports.

Also, I have a [repo](https://github.com/eruber/cookiecutter-template-converter) containing a command line utility that will convert a version 1 template file to a version 2 file.

### CODE REVIEW

**Comment by eruber** [comment]
Come to think of it, now that I am more familiar with the front-end of Cookiecutter (pre-jinja2 rendering) it might be more stream-lined to get rid of the code that processes v1 templates, and just convert all v1 files internally to version 2 files and then do the version 2 processing. The conversion is straightforward and it simplifies the code paths and maintenance.

**Comment by eruber** [comment]
In the course of being a user of this fork and having a cookiecutter.json file that is rather complex, I have added a few more features that make conditional processing of variables more intuitive. These features are:
      do_if (as opposed to skip_if)
      if_yes_skip_to : variable name
      if_no_skip_to  : variable name 

I am in the middle of testing these now...

**Comment by hackebrot** [comment]
Hi @eruber! 👋 

Thank you opening this PR and your efforts to improve Cookiecutter. 🙇 

We have decided to put the work on a new cookiecutter context specification on hold for until we have sponsors for this project. Please see @pydanny's comment on my PR for more info https://github.com/audreyr/cookiecutter/pull/848#issuecomment-259575460.

Sorry, I don't know if or when we will be in a position to integrate your changes and take on the extra maintenance work 😞

**Comment by kurtmckee** [comment]
I'm closing this PR due to its age and size.

**Pull request closed without merging**
