### PR TITLE
Return generated context from cookiecutter API

### PR DESCRIPTION
**Pull request by rmedaer**
I patched cookiecutter main function to return both result of `generate_files` function and generated context. Indeed the generated context is really useful for my application which using cookiecutter as Python module.

An example of usage: https://github.com/rmedaer/milhoja/blob/b1207e79/milhoja/milhoja.py#L178

### CODE REVIEW

**Comment by hackebrot** [comment]
Hi @rmedaer! 👋 

Thank you for this PR. I'm afraid, we will need to wait for the next major release to integrate this change, as it's breaking an existing API.

As you a workaround you can include a file in your template to store the context as a python dict with ``{{ cookiecutter }}``.

**Comment by theodesp** [comment]
@rmedaer Personally I don't particularly like this approach of returning 2 variables instead of one. How about adding a new CLI call to just provide you the context that was resolved?

**Comment by michaeljoseph** [comment]
Another workaround would be to read the context from the [`replay_dir`](https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/main.py#L84)?

**Comment by insspb** [comment]
Hi @rmedaer, thank you for contribution. And excuse us for long delay with answer
Please check #380 discussion. The resulting patch for #380 will make 'cookiecutter' a variable name. 
In this PR you are returning only part of context, not whole item. 
To be reusable such thing should return whole item.

**Comment by kurtmckee** [comment]
I'm closing this PR due to its age.

**Pull request closed without merging**
