### PR TITLE
added cookiecutter template

### PR DESCRIPTION
**Pull request by ttimbers**
I just created a new cookiecutter template for Python packages using Python poetry, GitHub Actions, Sphinx & Read the Docs and automatic version bumping via python-semantic-release. Default behaviour is to publish to testPyPI, however docs explain how to modify this to PyPI.

Was primarily developed for teaching students in the classroom but might be helpful to others.

### CODE REVIEW

**Comment by ssbarnea** [comment]
Read the docs, we no longer add new entries.

**Comment by hackebrot** [comment]
Hi @ttimbers! 👋 

Thank you for submitting a pull-request to Cookiecutter! 🍪 

A decision was made to not list templates on the project README file going forward. You can find out more about this on the [A Pantry Full of Cookiecutters](https://cookiecutter.readthedocs.io/en/1.7.0/README.html#a-pantry-full-of-cookiecutters) page of the documentation.

Sorry about that.

**Comment by hackebrot** [comment]
I don't appreciate that tone of voice, @ssbarnea. Please use empathy when talking and interacting with contributors to Cookiecutter. 😞

**Comment by ssbarnea** [comment]
@habnabit I rephrased the explanation. I also proposed https://github.com/cookiecutter/cookiecutter/pull/1331/files which should put an end to the incoming pull requests, but we need to be careful how we do the transition, assuring that we give people time to edit their topics, lots of projects do not have any added yet.

**Pull request closed without merging**
